#!/bin/sh

. "$(dirname "$0")/.common.sh"

trap_fail

pkg-config --exists libpcre || apt-get install -y libpcre3-dev

: ${nginx_url:=https://nginx.org/download/$(latest_nginx)}

dl_compile_and_install "$nginx_url" /srv/nginx "$DESTDIR" "" \
  --with-http_ssl_module --with-http_auth_request_module \
  --user=www-data --group=www-data

exit_succ
