#!/bin/sh

. "$(dirname "$0")/.common.sh"

trap_fail

: ${nodejs_txz:=$(dl_file "https://nodejs.org/dist/latest/$(latest_nodejs)")}

mkdir -p "$DESTDIR/opt"
tar xfvJ "$nodejs_txz" --strip-components=1 -C "$DESTDIR/opt" --exclude CHANGELOG.md --exclude LICENSE --exclude README.md

exit_succ
